### ISSUE TITLE
Problem with assignment of new accession numbers 

### ISSUE THREAD

**Issue by sjmack** [nmdp-bioinformatics/service-feature#24]
I'm using the swagger UI at http://feature.nmdp-bioinformatics.org

I'm not getting accession numbers > 1 when I POST multiple sequences for a given term and rank. When I try to GET sequences for accession numbers > 1 for a given term and rank, I get a 204 or a 500 error. 

For example, if I POST: 
{
  "locus": "HLA-V",
  "term": "exon",
  "rank": 4,
  "sequence": "GATC"
}

The response is: 

{
  "locus": "HLA-V",
  "term": "exon",
  "rank": 4,
  "accession": 1,
  "sequence": "GATC"
}

If I then POST:

{
  "locus": "HLA-V",
  "term": "exon",
  "rank": 4,
  "accession": 1,
  "sequence": "GATT"
}

The réponse is: 

{
  "locus": "HLA-V",
  "term": "exon",
  "rank": 4,
  "accession": 1,
  "sequence": "GATT"
}

Trying to GET: 

{
  "locus": "HLA-V",
  "term": "exon",
  "rank": 1,
  "accession": 1
}

Returns either (after multiple attempts) :

{
  "locus": "HLA-V",
  "term": "exon",
  "rank": 4,
  "accession": 1,
  "sequence": "GATC"
}

or 

{
  "code": 500,
  "message": "There was an error processing your request. It has been logged (ID 24a9085926b1e1c9)."
}

And, when I attempt to GET: 

{
  "locus": "HLA-V",
  "term": "exon",
  "rank": 1,
  "accession": 2
}

The return is either code 204 or 500. For an example of a 500 error in this instance see ID 48bdb77267e57118.

**Comment by mmaiers-nmdp** [comment]
I have been looking at this with @pbashyal-nmdp and we think we have a fix for it.

**Comment by mmaiers-nmdp** [comment]
I have submitted a pull request for the fix

**Comment by pbashyal-nmdp** [comment]
This fixes the accession number issue.

**POST** of the following 

```
{
  "locus": "HLA-V",
  "term": "exon",
  "rank": 4,
  "accession": 0,
  "sequence": "GATC"
}
```

will return  accession of 1

**POST** of the following 

```
{
  "locus": "HLA-V",
  "term": "exon",
  "rank": 4,
  "accession": 0,
  "sequence": "GATT"
}
```

will return accession of 2

**Comment by pbashyal-nmdp** [comment]
63804e3a944bf185fbea95706bae1613f2267da3 fixed the issue.
