### ISSUE TITLE
Doc for sequence mentions DNA alphabet but is never enforced

### ISSUE THREAD

**Issue by heuermh** [nmdp-bioinformatics/service-feature#30]
Documentation for sequence attribute mentions DNA alphabet
https://github.com/nmdp-bioinformatics/service-feature/blob/master/resource/src/main/java/org/nmdp/service/feature/resource/FeatureRequest.java#L72

but is never enforced.

Consider:
- remove doc and allow any characters
- enforce DNA alphabet with no ambiguity
- enforce DNA alphabet (including IUPAC ambiguity) using biojava
- provide alphabet request attribute `{DNA, RNA, AA/PROTEIN}` and enforce using biojava

**Comment by heuermh** [comment]
Ping @mmaiers-nmdp @bmilius-nmdp @epearson-nmdp @pbashyal-nmdp for comment.

Will be interesting to see how many invalid sequences have been registered to date.

**Comment by sjmack** [comment]
I think that the service could be used for both DNA and peptide sequences, if we can find the appropriate SO terms for the peptide sequences. I also think that allowing IUPAC ambiguity could be useful assuming that we can create a meta-function that can identify any/all pairs of unambiguous feature sequences that match a given ambiguous sequence. I'm also open to storing RNA sequences, although again there'd have to be a meta-function to interchange identify corresponding DNA sequence. So, I'm in favor of bullet 4.

**Comment by mmaiers-nmdp** [comment]
I think we should keep the microservices micro.   One for nucleotide sequences.  One for nucleotide sequences with ambiguity.  One for amino acid sequences.  Etc.  And keep this one Watson & Crick only ([ACGT]).

One reason not to allow amino acid sequences in this service as it is is that it breaks the paradigm of locus/term/rank where term is "exon".  For example HLA-B codon 183 is constructed from on nucleotide from exon 3 and 2 nucleotides from exon 4.  

My vote is: different service (or different objects/verbs in this service)

**Comment by sjmack** [comment]
Okay. As long as we have the meta-functions to be able to talk to all of these micro-services.
