### ISSUE TITLE
HML input

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/service-feature#47]
We would like to be able to submit HML with consensus to the service and have it generate GFE names for each allele; and output a new HML

**Comment by heuermh** [comment]
Does this issue belong here or in https://github.com/nmdp-bioinformatics/service-gfe-submission?

**Comment by mmaiers-nmdp** [comment]
yes, moved

**Comment by mmaiers-nmdp** [comment]
yes, moved
